apiVersion: v1
kind: Service
metadata:
  name: bd-k8s-test
  labels:
    name: bd-k8s-test
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    name: bd-k8s-test
